coverage:
  status:
    project:
      # Default is a misnomer and these settings are not used as a fallback
      default:
        target: 60%  # Overall project/repo coverage
        only_pulls: true

comment:
  show_carryforward_flags: true

# Use `carryforward: true` to avoid misreporting coverage due to slow running cluster tests
flag_management:
  default_rules:
    carryforward: true
