coverage:
  status:
    project:
      # Default is a misnomer and these settings are not used as a fallback
      default:
        target: 60%  # Overall project/repo coverage
        only_pulls: true

comment:
  show_carryforward_flags: true

# Wait until 2x Julia unit tests jobs and 3x Cluster Test jobs have completed before reporting
# coverage. Avoids reporting coverage too early which would show a misleading drop in code
# coverage.
# https://docs.codecov.com/docs/notifications#preventing-notifications-until-after-n-builds
comment:
  after_n_builds: 5
